name: ci by raj

on:
  push:

jobs:
  build: # job ka naam
    runs-on: ubuntu-latest # GitHub ka free Ubuntu runner

    steps:
      - name: Checkout code # code ko runner me clone karta hai
        uses: actions/checkout@v4

      - name: Set up Docker Buildx # Docker build setup
        uses: docker/setup-buildx-action@v3